# Generated by Django 3.1.4 on 2020-12-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_e_commerce', '0004_auto_20201205_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
